### ISSUE TITLE
empty JUNIT file raise error

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-control-server#31]
`junit2dict()` returns an empty dict if the input is empty. This is the reason why we get the following error after:

```
[Tue May 23 09:20:29.318215 2017] [:error] [pid 10427] [client 198.154.188.41:39992] KeyError: 'time'
[Tue May 23 10:09:37.547995 2017] [:error] [pid 10385] [client 198.154.188.41:40040] mod_wsgi (pid=10385): Exception occurred processing WSGI script '/usr/share/dci-api/wsgi.py'.
[Tue May 23 10:09:37.549091 2017] [:error] [pid 10385] [client 198.154.188.41:40040] IOError: failed to write data
[Tue May 23 12:40:59.037056 2017] [:error] [pid 10384] [client 198.154.188.41:40150] mod_wsgi (pid=10384): Exception occurred processing WSGI script '/usr/share/dci-api/wsgi.py'.
[Tue May 23 12:40:59.037222 2017] [:error] [pid 10384] [client 198.154.188.41:40150] Traceback (most recent call last):
[Tue May 23 12:40:59.037321 2017] [:error] [pid 10384] [client 198.154.188.41:40150]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
[Tue May 23 12:40:59.038113 2017] [:error] [pid 10384] [client 198.154.188.41:40150]     return self.wsgi_app(environ, start_response)
[Tue May 23 12:40:59.038138 2017] [:error] [pid 10384] [client 198.154.188.41:40150]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
[Tue May 23 12:40:59.038182 2017] [:error] [pid 10384] [client 198.154.188.41:40150]     response = self.make_response(self.handle_exception(e))
[Tue May 23 12:40:59.038202 2017] [:error] [pid 10384] [client 198.154.188.41:40150]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
[Tue May 23 12:40:59.038226 2017] [:error] [pid 10384] [client 198.154.188.41:40150]     reraise(exc_type, exc_value, tb)
[Tue May 23 12:40:59.038238 2017] [:error] [pid 10384] [client 198.154.188.41:40150]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Tue May 23 12:40:59.038257 2017] [:error] [pid 10384] [client 198.154.188.41:40150]     response = self.full_dispatch_request()
[Tue May 23 12:40:59.038269 2017] [:error] [pid 10384] [client 198.154.188.41:40150]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Tue May 23 12:40:59.038286 2017] [:error] [pid 10384] [client 198.154.188.41:40150]     rv = self.handle_user_exception(e)
[Tue May 23 12:40:59.038297 2017] [:error] [pid 10384] [client 198.154.188.41:40150]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Tue May 23 12:40:59.038314 2017] [:error] [pid 10384] [client 198.154.188.41:40150]     reraise(exc_type, exc_value, tb)
[Tue May 23 12:40:59.038325 2017] [:error] [pid 10384] [client 198.154.188.41:40150]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Tue May 23 12:40:59.038341 2017] [:error] [pid 10384] [client 198.154.188.41:40150]     rv = self.dispatch_request()
[Tue May 23 12:40:59.038352 2017] [:error] [pid 10384] [client 198.154.188.41:40150]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Tue May 23 12:40:59.038389 2017] [:error] [pid 10384] [client 198.154.188.41:40150]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue May 23 12:40:59.038404 2017] [:error] [pid 10384] [client 198.154.188.41:40150]   File "/usr/lib/python2.7/site-packages/dci/auth.py", line 72, in decorated
[Tue May 23 12:40:59.038525 2017] [:error] [pid 10384] [client 198.154.188.41:40150]     return f(mechanism.identity, *args, **kwargs)
[Tue May 23 12:40:59.038556 2017] [:error] [pid 10384] [client 198.154.188.41:40150]   File "/usr/lib/python2.7/site-packages/dci/api/v1/files.py", line 127, in create_files
[Tue May 23 12:40:59.038744 2017] [:error] [pid 10384] [client 198.154.188.41:40150]     'time': junit['time']
[Tue May 23 12:40:59.038804 2017] [:error] [pid 10384] [client 198.154.188.41:40150] KeyError: 'time'
```

I think we should instead raise an exception and refuse the invalid input.

**Comment by guillaumevincent** [comment]
I agree. But we need to change tests: https://github.com/redhat-cip/dci-control-server/blob/master/tests/api/v1/test_transformations.py#L116-L127

**Comment by guillaumevincent** [comment]
This is an enhancement, not really important for now
if it breaks something we will open another issue.
I close
