### ISSUE TITLE
AttributeError: '_RetryBody' object has no attribute 'close'

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-control-server#50]
Follow up of an component upload failure:
```
        "(755/755): rhosp-director- 99% [===============-]  15 MB/s | 2.0 GB   00:00 ETA ", 
        "", 
        "(755/755): rhosp-director-images-12.0-20171102.3.el7ost.no | 1.2 GB   03:04     ", 
        "Spawning worker 0 with 755 pkgs", 
        "Workers Finished", 
        "Saving Primary metadata", 
        "Saving file lists metadata", 
        "Saving other metadata", 
        "Generating sqlite DBs", 
        "Sqlite DBs complete", 
        "Uploading bits...", 
        "  Upload of archive.tar has failed for component RH7-RHOS-12.0 2017-11-02.3: <!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">", 
        "<html><head>", 
        "<title>500 Internal Server Error</title>", 
        "</head><body>", 
        "<h1>Internal Server Error</h1>", 
        "<p>The server encountered an internal error or", 
        "misconfiguration and was unable to complete", 
        "your request.</p>", 
        "<p>Please contact the server administrator at ", 
        " distributed-ci@redhat.com to inform them of the time this error occurred,", 
        " and the actions you performed just before this error.</p>", 
        "<p>More information about this error may be available", 
        "in the server error log.</p>", 
        "</body></html>"
```

On the server-side:

```
(...)
[Fri Nov 03 13:25:35.461303 2017] [:error] [pid 12534] [client 163.244.22.11:13223] AttributeError: '_RetryBody' object has no attribute 'close', referer: https://www.distributed-ci.io/jobs/a86dee45-33f3-49e6-8adc-ec2a48e189e4/jobStates
[Fri Nov 03 13:25:35.480349 2017] [:error] [pid 12745] [client 163.244.22.11:13226] mod_wsgi (pid=12745): Exception occurred processing WSGI script '/usr/share/dci-api/wsgi.py'., referer: https://www.distributed-ci.io/jobs/a86dee45-33f3-49e6-8adc-ec2a48e189e4/jobStates
[Fri Nov 03 13:25:35.480403 2017] [:error] [pid 12745] [client 163.244.22.11:13226] AttributeError: '_RetryBody' object has no attribute 'close', referer: https://www.distributed-ci.io/jobs/a86dee45-33f3-49e6-8adc-ec2a48e189e4/jobStates
[Fri Nov 03 13:25:35.633957 2017] [:error] [pid 11935] [client 163.244.22.11:13227] mod_wsgi (pid=11935): Exception occurred processing WSGI script '/usr/share/dci-api/wsgi.py'., referer: https://www.distributed-ci.io/jobs/a86dee45-33f3-49e6-8adc-ec2a48e189e4/jobStates
[Fri Nov 03 13:25:35.634008 2017] [:error] [pid 11935] [client 163.244.22.11:13227] AttributeError: '_RetryBody' object has no attribute 'close', referer: https://www.distributed-ci.io/jobs/a86dee45-33f3-49e6-8adc-ec2a48e189e4/jobStates
[Fri Nov 03 13:25:35.851327 2017] [:error] [pid 12950] [client 163.244.22.11:13063] mod_wsgi (pid=12950): Exception occurred processing WSGI script '/usr/share/dci-api/wsgi.py'., referer: https://www.distributed-ci.io/jobs/a86dee45-33f3-49e6-8adc-ec2a48e189e4/jobStates
[Fri Nov 03 13:25:35.851368 2017] [:error] [pid 12950] [client 163.244.22.11:13063] AttributeError: '_RetryBody' object has no attribute 'close', referer: https://www.distributed-ci.io/jobs/a86dee45-33f3-49e6-8adc-ec2a48e189e4/jobStates
[Fri Nov 03 13:25:36.023622 2017] [:error] [pid 12838] [client 163.244.22.11:13221] mod_wsgi (pid=12838): Exception occurred processing WSGI script '/usr/share/dci-api/wsgi.py'., referer: https://www.distributed-ci.io/jobs/a86dee45-33f3-49e6-8adc-ec2a48e189e4/jobStates
[Fri Nov 03 13:25:36.023669 2017] [:error] [pid 12838] [client 163.244.22.11:13221] AttributeError: '_RetryBody' object has no attribute 'close', referer: https://www.distributed-ci.io/jobs/a86dee45-33f3-49e6-8adc-ec2a48e189e4/jobStates
[Fri Nov 03 13:25:36.084937 2017] [:error] [pid 12129] [client 163.244.22.11:13222] mod_wsgi (pid=12129): Exception occurred processing WSGI script '/usr/share/dci-api/wsgi.py'., referer: https://www.distributed-ci.io/jobs/a86dee45-33f3-49e6-8adc-ec2a48e189e4/jobStates
[Fri Nov 03 13:25:36.084974 2017] [:error] [pid 12129] [client 163.244.22.11:13222] AttributeError: '_RetryBody' object has no attribute 'close', referer: https://www.distributed-ci.io/jobs/a86dee45-33f3-49e6-8adc-ec2a48e189e4/jobStates
[Fri Nov 03 13:25:36.126686 2017] [:error] [pid 12534] [client 163.244.22.11:13223] mod_wsgi (pid=12534): Exception occurred processing WSGI script '/usr/share/dci-api/wsgi.py'., referer: https://www.distributed-ci.io/jobs/a86dee45-33f3-49e6-8adc-ec2a48e189e4/jobStates
[Fri Nov 03 13:25:36.126724 2017] [:error] [pid 12534] [client 163.244.22.11:13223] AttributeError: '_RetryBody' object has no attribute 'close', referer: https://www.distributed-ci.io/jobs/a86dee45-33f3-49e6-8adc-ec2a48e189e4/jobStates
[Fri Nov 03 13:41:37.310178 2017] [:error] [pid 12129] [client 38.145.32.185:48290] mod_wsgi (pid=12129): Exception occurred processing WSGI script '/usr/share/dci-api/wsgi.py'.
[Fri Nov 03 13:41:37.310244 2017] [:error] [pid 12129] [client 38.145.32.185:48290] AttributeError: '_RetryBody' object has no attribute 'close'
[Fri Nov 03 14:01:48.891321 2017] [:error] [pid 12745] [client 38.145.32.191:46416] mod_wsgi (pid=12745): Exception occurred processing WSGI script '/usr/share/dci-api/wsgi.py'.
[Fri Nov 03 14:01:48.891393 2017] [:error] [pid 12745] [client 38.145.32.191:46416] Traceback (most recent call last):
[Fri Nov 03 14:01:48.891417 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
[Fri Nov 03 14:01:48.891584 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     return self.wsgi_app(environ, start_response)
[Fri Nov 03 14:01:48.891618 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
[Fri Nov 03 14:01:48.891642 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     response = self.make_response(self.handle_exception(e))
[Fri Nov 03 14:01:48.891649 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
[Fri Nov 03 14:01:48.891659 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     reraise(exc_type, exc_value, tb)
[Fri Nov 03 14:01:48.891664 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Fri Nov 03 14:01:48.891671 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     response = self.full_dispatch_request()
[Fri Nov 03 14:01:48.891678 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Fri Nov 03 14:01:48.891685 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     rv = self.handle_user_exception(e)
[Fri Nov 03 14:01:48.891690 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Fri Nov 03 14:01:48.891698 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     reraise(exc_type, exc_value, tb)
[Fri Nov 03 14:01:48.891702 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Fri Nov 03 14:01:48.891710 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     rv = self.dispatch_request()
[Fri Nov 03 14:01:48.891715 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Fri Nov 03 14:01:48.891753 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     return self.view_functions[rule.endpoint](**req.view_args)
[Fri Nov 03 14:01:48.891760 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/dci/decorators.py", line 69, in decorated
[Fri Nov 03 14:01:48.891780 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     return f(auth_scheme.identity, *args, **kwargs)
[Fri Nov 03 14:01:48.891787 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/dci/api/v1/components.py", line 246, in upload_component_file
[Fri Nov 03 14:01:48.891810 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     swift.upload(file_path, flask.request.stream)
[Fri Nov 03 14:01:48.891817 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/dci/stores/swift.py", line 69, in upload
[Fri Nov 03 14:01:48.891828 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     self.connection.put_object(self.container, file_path, iterable)
[Fri Nov 03 14:01:48.891833 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/swiftclient/client.py", line 1829, in put_object
[Fri Nov 03 14:01:48.891843 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     response_dict=response_dict)
[Fri Nov 03 14:01:48.891848 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/swiftclient/client.py", line 1715, in _retry
[Fri Nov 03 14:01:48.891855 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     reset_func(func, *args, **kwargs)
[Fri Nov 03 14:01:48.891860 2017] [:error] [pid 12745] [client 38.145.32.191:46416]   File "/usr/lib/python2.7/site-packages/swiftclient/client.py", line 1809, in _default_reset
[Fri Nov 03 14:01:48.891888 2017] [:error] [pid 12745] [client 38.145.32.191:46416]     % (container, obj))
[Fri Nov 03 14:01:48.891917 2017] [:error] [pid 12745] [client 38.145.32.191:46416] ClientException: put_object('dci_components', 'e33fe610-f7ac-4bb5-9c37-423b3ffdd245/6d30d2fa-dbee-4389-81d0-04e7079c2df3/36ba1f71-fd5a-4c51-9ad3-de14b1f0f6a6', ...) failure and no ability to reset contents for reupload.
```

**Comment by Spredzy** [comment]
@Goneri I think this should be solved with the use of dci-feeder-api. I'll go ahead and close this one, please feel free to re-open if needed.
