### ISSUE TITLE
Dockerfile: tox is not working

### ISSUE THREAD

**Issue by dsavineau** [redhat-cip/dci-control-server#63]
```
$ docker exec -it dcidevenv_api_1 bash
pep8 develop-inst-noop: /opt/dci-control-server
pep8 installed: Error [Errno 2] No such file or directory while executing command git config --get-regexp remote\..*\.url,cannot determine version of editable source in /opt/dci-control-server (git command not found in path),alembic==0.9.9,asn1crypto==0.24.0,astroid==1.4.9,attrs==18.1.0,Babel==2.5.3,backports.functools-lru-cache==1.5,certifi==2018.4.16,cffi==1.11.5,chardet==3.0.4,click==6.7,configparser==3.5.0,coverage==4.5.1,cryptography==2.2.2,-e dci==0.2.1,dciauth==2.0.2,dciclient==0.4,debtcollector==1.19.0,enum34==1.1.6,flake8==2.4.1,Flask==0.10.1,funcsigs==1.0.2,futures==3.2.0,idna==2.6,ipaddress==1.0.22,iso8601==0.1.12,isort==4.3.4,itsdangerous==0.24,Jinja2==2.10,keystoneauth1==3.6.0,lazy-object-proxy==1.3.1,lxml==4.2.1,Mako==1.0.7,MarkupSafe==1.0,mccabe==0.3.1,mock==2.0.0,monotonic==1.5,more-itertools==4.1.0,msgpack==0.5.6,netaddr==0.7.19,netifaces==0.10.7,os-service-types==1.2.0,oslo.config==6.2.0,oslo.i18n==3.20.0,oslo.serialization==2.25.0,oslo.utils==3.36.1,passlib==1.7.1,pbr==4.0.2,pep8==1.7.1,pluggy==0.6.0,prettytable==0.7.2,psycopg2==2.7.4,py==1.5.3,pycparser==2.18,pyflakes==0.8.1,PyJWT==1.6.1,pylint==1.6.4,pyOpenSSL==17.5.0,pyparsing==2.2.0,pytest==3.5.1,pytest-cov==2.5.1,python-dateutil==2.7.2,python-editor==1.0.3,python-keystoneclient==3.16.0,python-swiftclient==3.5.0,pytz==2018.4,PyYAML==3.12,pyzmq==17.0.0,requests==2.18.4,rfc3986==1.1.0,six==1.11.0,SQLAlchemy==1.2.7,SQLAlchemy-Utils==0.33.3,stevedore==1.28.0,tox==3.0.0,urllib3==1.22,virtualenv==15.2.0,voluptuous==0.10.5,Werkzeug==0.14.1,wrapt==1.10.11
pep8 runtests: PYTHONHASHSEED='307724482'
pep8 runtests: commands[0] | flake8
py27 develop-inst-noop: /opt/dci-control-server
py27 installed: Error [Errno 2] No such file or directory while executing command git config --get-regexp remote\..*\.url,cannot determine version of editable source in /opt/dci-control-server (git command not found in path),alembic==0.9.9,asn1crypto==0.24.0,astroid==1.4.9,attrs==18.1.0,Babel==2.5.3,backports.functools-lru-cache==1.5,certifi==2018.4.16,cffi==1.11.5,chardet==3.0.4,click==6.7,configparser==3.5.0,coverage==4.5.1,cryptography==2.2.2,-e dci==0.2.1,dciauth==2.0.2,dciclient==0.4,debtcollector==1.19.0,enum34==1.1.6,flake8==2.4.1,Flask==0.10.1,funcsigs==1.0.2,futures==3.2.0,idna==2.6,ipaddress==1.0.22,iso8601==0.1.12,isort==4.3.4,itsdangerous==0.24,Jinja2==2.10,keystoneauth1==3.6.0,lazy-object-proxy==1.3.1,lxml==4.2.1,Mako==1.0.7,MarkupSafe==1.0,mccabe==0.3.1,mock==2.0.0,monotonic==1.5,more-itertools==4.1.0,msgpack==0.5.6,netaddr==0.7.19,netifaces==0.10.7,os-service-types==1.2.0,oslo.config==6.2.0,oslo.i18n==3.20.0,oslo.serialization==2.25.0,oslo.utils==3.36.1,passlib==1.7.1,pbr==4.0.2,pep8==1.7.1,pluggy==0.6.0,prettytable==0.7.2,psycopg2==2.7.4,py==1.5.3,pycparser==2.18,pyflakes==0.8.1,PyJWT==1.6.1,pylint==1.6.4,pyOpenSSL==17.5.0,pyparsing==2.2.0,pytest==3.5.1,pytest-cov==2.5.1,python-dateutil==2.7.2,python-editor==1.0.3,python-keystoneclient==3.16.0,python-swiftclient==3.5.0,pytz==2018.4,PyYAML==3.12,pyzmq==17.0.0,requests==2.18.4,rfc3986==1.1.0,six==1.11.0,SQLAlchemy==1.2.7,SQLAlchemy-Utils==0.33.3,stevedore==1.28.0,tox==3.0.0,urllib3==1.22,virtualenv==15.2.0,voluptuous==0.10.5,Werkzeug==0.14.1,wrapt==1.10.11
py27 runtests: PYTHONHASHSEED='307724482'
py27 runtests: commands[0] | sh ./scripts/start_db.sh
+ DCI_DB_DIR=.db_dir
+ DCI_DB_USER=dci
+ DCI_DB_PASS=dci
+ DCI_DB_NAME=dci
+++ dirname ./scripts/start_db.sh
++ cd ./scripts/..
++ pwd
+ DCI_DB_DIR=/opt/dci-control-server/.db_dir
+ '[' '!' -z 1 ']'
+ exit 0
py27 runtests: commands[1] | py.test -v tests
/opt/dci-control-server/.tox/py27/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/opt/dci-control-server/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 371, in _importconftest
    mod = conftestpath.pyimport()
  File "/opt/dci-control-server/.tox/py27/lib/python2.7/site-packages/py/_path/local.py", line 686, in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
ImportMismatchError: ('tests.conftest', '/opt/dci/tests/conftest.py', local('/opt/dci-control-server/tests/conftest.py'))
ERROR: could not load /opt/dci-control-server/tests/conftest.py

ERROR: InvocationError for command '/opt/dci-control-server/.tox/py27/bin/py.test -v tests' (exited with code 4)
py34 develop-inst-noop: /opt/dci-control-server
py34 installed: Error [Errno 2] No such file or directory: 'git' while executing command git config --get-regexp remote\..*\.url,cannot determine version of editable source in /opt/dci-control-server (git command not found in path),alembic==0.9.9,asn1crypto==0.24.0,astroid==1.4.9,attrs==18.1.0,Babel==2.5.3,certifi==2018.4.16,cffi==1.11.5,chardet==3.0.4,click==6.7,coverage==4.5.1,cryptography==2.2.2,-e dci==0.2.1,dciauth==2.0.2,dciclient==0.4,debtcollector==1.19.0,flake8==2.4.1,Flask==0.10.1,idna==2.6,iso8601==0.1.12,isort==4.3.4,itsdangerous==0.24,Jinja2==2.10,keystoneauth1==3.6.0,lazy-object-proxy==1.3.1,lxml==4.2.1,Mako==1.0.7,MarkupSafe==1.0,mccabe==0.3.1,mock==2.0.0,monotonic==1.5,more-itertools==4.1.0,msgpack==0.5.6,netaddr==0.7.19,netifaces==0.10.7,os-service-types==1.2.0,oslo.config==6.2.0,oslo.i18n==3.20.0,oslo.serialization==2.25.0,oslo.utils==3.36.1,passlib==1.7.1,pbr==4.0.2,pep8==1.7.1,pluggy==0.6.0,prettytable==0.7.2,psycopg2==2.7.4,py==1.5.3,pycparser==2.18,pyflakes==0.8.1,PyJWT==1.6.1,pylint==1.6.4,pyOpenSSL==17.5.0,pyparsing==2.2.0,pytest==3.5.1,pytest-cov==2.5.1,python-dateutil==2.7.2,python-editor==1.0.3,python-keystoneclient==3.16.0,python-swiftclient==3.5.0,pytz==2018.4,PyYAML==3.12,pyzmq==17.0.0,requests==2.18.4,rfc3986==1.1.0,six==1.11.0,SQLAlchemy==1.2.7,SQLAlchemy-Utils==0.33.3,stevedore==1.28.0,tox==3.0.0,urllib3==1.22,virtualenv==15.2.0,voluptuous==0.10.5,Werkzeug==0.14.1,wrapt==1.10.11
py34 runtests: PYTHONHASHSEED='307724482'
py34 runtests: commands[0] | sh ./scripts/start_db.sh
+ DCI_DB_DIR=.db_dir
+ DCI_DB_USER=dci
+ DCI_DB_PASS=dci
+ DCI_DB_NAME=dci
+++ dirname ./scripts/start_db.sh
++ cd ./scripts/..
++ pwd
+ DCI_DB_DIR=/opt/dci-control-server/.db_dir
+ '[' '!' -z 1 ']'
+ exit 0
py34 runtests: commands[1] | py.test -v tests
/opt/dci-control-server/.tox/py34/lib/python3.4/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/opt/dci-control-server/.tox/py34/lib/python3.4/site-packages/_pytest/config.py", line 334, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/opt/dci-control-server/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/dci-control-server/.tox/py34/lib/python3.4/site-packages/_pytest/config.py", line 365, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/opt/dci-control-server/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/dci-control-server/.tox/py34/lib/python3.4/site-packages/_pytest/config.py", line 371, in _importconftest
    mod = conftestpath.pyimport()
  File "/opt/dci-control-server/.tox/py34/lib/python3.4/site-packages/py/_path/local.py", line 686, in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
py._path.local.ImportMismatchError: ('tests.conftest', '/opt/dci/tests/conftest.py', local('/opt/dci-control-server/tests/conftest.py'))
ERROR: could not load /opt/dci-control-server/tests/conftest.py

ERROR: InvocationError for command '/opt/dci-control-server/.tox/py34/bin/py.test -v tests' (exited with code 4)
___________________________________ summary ____________________________________
  pep8: commands succeeded
ERROR:   py27: commands failed
ERROR:   py34: commands failed
```

**Comment by goneri** [comment]
Could you manually install git in the container before.

**Comment by dsavineau** [comment]
installing git doesn't change anything, it only remove the error about git (Error [Errno 2] No such file or directory while executing command git config --get-regexp remote\..*\.url,cannot determine version of editable source in /opt/dci-control-server (git command not found in path))

**Comment by guillaumevincent** [comment]
It's probably not related but it works for me with sh instead of bash. SeLinux disabled in docker conf and volumes cleaned.

**Comment by dsavineau** [comment]
I probably had some leftovers somewhere. After building the env from scratch it's now working...
Anyway I will create a review about the git error.
